In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("housing.csv")

df.shape

(20640, 10)

In [2]:
pd.__version__

'2.1.0'

In [3]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [4]:
rooms = df['total_rooms'].isna().sum()
print(rooms)

0


In [5]:
bedrooms = df['total_bedrooms'].isna().sum()
print(bedrooms)

207


In [6]:
unique = df['ocean_proximity'].unique()
print(unique)

['NEAR BAY' '<1H OCEAN' 'INLAND' 'NEAR OCEAN' 'ISLAND']


In [7]:
df_bay = df[df['ocean_proximity'] == 'NEAR BAY']

print(df_bay.head())

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY  


In [8]:
print(df_bay['median_house_value'].mean())

259212.31179039303


In [9]:
df_fillnan = df_bay['median_house_value'].fillna(0)
df_fillnan.head()

0    452600.0
1    358500.0
2    352100.0
3    341300.0
4    342200.0
Name: median_house_value, dtype: float64

In [10]:
print(df_fillnan[1].mean())

358500.0


In [11]:
df = df[df['ocean_proximity'] == 'ISLAND']

In [12]:
df_selection = df[['housing_median_age', 'total_rooms', 'total_bedrooms']]

In [13]:
X = df_selection.to_numpy()
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [20]:
XTX = X.T.dot(X)
XTX 

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [21]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [22]:
y=[950, 1300, 800, 1000, 1300]
y

[950, 1300, 800, 1000, 1300]

In [24]:
w = XTX_inv.dot(X.T).dot(y)
w

array([23.12330961, -1.48124183,  5.69922946])